// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditDiff = { "format": "unified", unified_diff: string, } | { "format": "replace", old: string, new: string, };
